# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_freezerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfimage',
            name='rectjson',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='shelfgoods',
            name='upc',
            field=models.CharField(default='', max_length=20),
        ),
    ]
