# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190918_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfimage',
            name='picid',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
