# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_shelfimage_picid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfimage',
            name='image_name',
        ),
        migrations.AddField(
            model_name='shelfimage',
            name='rectsource',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
