# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-25 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190924_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfimage',
            name='picurl',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelfimage',
            name='rectsource',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='shelfimage',
            name='shelfid',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shelfimage',
            name='source',
            field=models.CharField(default='', max_length=200),
        ),
    ]
