# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190925_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfimage',
            name='resultsource',
            field=models.CharField(default='', max_length=200),
        ),
    ]
