# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-10 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20191010_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerimage',
            name='visual',
            field=models.URLField(default=''),
        ),
    ]
