# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_freezerimage_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfgoods',
            name='baidu_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
