# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20191014_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstGoodsSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField(db_index=True)),
                ('upc', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('predict_sales_amount', models.IntegerField()),
                ('template_shop_ids', models.CharField(max_length=100)),
            ],
        ),
    ]
