# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_firstgoodsselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_sales_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField()),
                ('class_three_id', models.IntegerField()),
                ('nextday_predict_sales', models.IntegerField()),
                ('next_day', models.CharField(max_length=32)),
                ('upc', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('day_sales', models.IntegerField()),
                ('nextdays_predict_sales', models.TextField()),
                ('day_week', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ai_sales_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField()),
                ('upc', models.CharField(max_length=20)),
                ('order_sale', models.IntegerField()),
                ('predict_sale', models.IntegerField()),
                ('min_stock', models.IntegerField()),
                ('max_stock', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('create_date', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='firstgoodsselection',
            name='mch_code',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='firstgoodsselection',
            name='mch_goods_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
