# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_goodsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_sales_order',
            name='erp_shop_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ai_sales_order',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
