# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-05 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_auto_20191105_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai_sales_order',
            name='status',
        ),
    ]
