# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-07 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_remove_ai_sales_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_sales_order',
            name='goods_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
