# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-13 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_ai_sales_order_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstgoodsselection',
            name='predict_sales_num',
            field=models.IntegerField(default=0),
        ),
    ]
