# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_firstgoodsselection_predict_sales_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstgoodsselection',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
