# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_ai_weather_categoryarearatio_categoryintimacy_categorylevelrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryAreaRatio',
        ),
        migrations.DeleteModel(
            name='CategoryIntimacy',
        ),
        migrations.DeleteModel(
            name='CategoryLevelRelation',
        ),
    ]
