# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0027_auto_20191118_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSelectionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.IntegerField(db_index=True)),
                ('batch_id', models.IntegerField(default=1)),
                ('upc', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('predict_sales_amount', models.IntegerField()),
                ('predict_sales_num', models.FloatField(default=0.0)),
                ('template_shop_ids', models.CharField(max_length=100)),
                ('mch_goods_code', models.CharField(default='', max_length=100)),
                ('mch_code', models.IntegerField(default=2)),
                ('create_time', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='firstgoodsselection',
            name='batch_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='firstgoodsselection',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
