# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0032_auto_20191126_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='allworkflowbatch',
            name='auto_display_calculate_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allworkflowbatch',
            name='order_goods_calculate_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allworkflowbatch',
            name='select_goods_calculate_time',
            field=models.IntegerField(default=0),
        ),
    ]
