# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-27 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0033_auto_20191127_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='allworkflowbatch',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allworkflowbatch',
            name='select_goods_status',
            field=models.IntegerField(default=0),
        ),
    ]
