# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0034_auto_20191127_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfdisplaydebug',
            name='calculate_time',
            field=models.IntegerField(default=0),
        ),
    ]
