# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_shelfdisplaydebug_calculate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstgoodsselection',
            name='uc_shopid',
            field=models.IntegerField(default=806),
        ),
        migrations.AddField(
            model_name='goodsselectionhistory',
            name='uc_shopid',
            field=models.IntegerField(default=806),
        ),
    ]
