# Generated by Django 2.0 on 2019-12-09 10:50

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0036_auto_20191129_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgb_source', models.ImageField(max_length=200, upload_to=goods.models.arm_image_upload_source)),
                ('depth_source', models.ImageField(max_length=200, upload_to=goods.models.arm_image_upload_source)),
                ('table_z', models.IntegerField(default=0)),
                ('result', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
            ],
        ),
    ]
