# Generated by Django 2.0 on 2019-12-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0037_armimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='allworkflowbatch',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='allworkflowbatch',
            name='erp_warehouse_id',
            field=models.IntegerField(default=None),
        ),
    ]
