# Generated by Django 2.0 on 2019-12-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0038_auto_20191212_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allworkflowbatch',
            name='erp_warehouse_id',
        ),
    ]
