# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-03 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_mengniufreezerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfdisplaydebuggoods',
            name='shelf_display_debug',
        ),
        migrations.RenameField(
            model_name='shelfdisplaydebug',
            old_name='category_intimacy_source',
            new_name='old_display_source',
        ),
        migrations.DeleteModel(
            name='ShelfDisplayDebugGoods',
        ),
    ]
