# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0042_auto_20200103_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allworkflowbatch',
            name='batch_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
