# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-01-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0043_auto_20200107_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfdisplaydebug',
            name='batch_id',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
